wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.27
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.5
      5: 0.10.27
      8:
      - 5
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 25
gamma:
  desc: null
  value: 0.1
learning_rate:
  desc: null
  value: 0.001
num_workers:
  desc: null
  value: 2
optimizer:
  desc: null
  value: adam
step_size:
  desc: null
  value: 7
